---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
#  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[apache_tomcat::default]
    attributes:
      java:
        install_flavor: 'oracle'
        jdk_version:    '8'
        java_home:      '/usr/lib/jvm/java-1.8.0-oracle'
        oracle:
          accept_oracle_download_terms: true
