AllCops:
  Exclude:
    - 'Guardfile'

SingleSpaceBeforeFirstArg:
  Exclude:
    - "**/metadata.rb"

# In some cases it makes sense to let the line
# exceed 80 characters, especially in specs.
Metrics/LineLength:
  Max: 100

LeadingCommentSpace:
  Enabled: false

Documentation:
  Enabled: false

# This is a really lame cop - especially when the methods contain Chef resources
# that are lengthy.
Metrics/AbcSize:
  Max: 47

# Also lame...
Metrics/MethodLength:
  Max: 30

# Cop has no sense of style
Style/ClosingParenthesisIndentation:
  Enabled: false
